services:
    payment-service:
        container_name: payment-service
        build:
            context: ./
            dockerfile: ./backend/payment-service/Dockerfile.dev
        ports:
            - '3005:3000'
        environment:
            DATABASE_URL: 'postgresql://ecommerce_owner:j3DWlwT8YqXC@ep-lively-lake-a2fgz6pc.eu-central-1.aws.neon.tech/ecommerce?sslmode=require'
        volumes:
            - ./backend/payment-service:/home/node/app

volumes:
    user-service-db-data:
    payment-service-db-data:
    product-service-db-data:
    auth-service-db-data:
    cart-service-db-data:
