services:
    payment-service:
        container_name: payment-service
        build:
            context: ./
            dockerfile: ./backend/payment-service/Dockerfile.dev
        ports:
            - '3005:3000'
        environment:
            DATABASE_URL: 'postgres://postgres:postgres@payment-service-db:5432/payment-service'
        volumes:
            - ./backend/payment-service:/home/node/app
        depends_on:
            - payment-service-db

    payment-service-db:
        container_name: payment-service-db
        image: postgres:latest
        ports:
            - '5435:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB_PAYMENT}
        volumes:
            - payment-service-db-data:/var/lib/postgresql/data
volumes:
    user-service-db-data:
    auth-service-db-data:
    cart-service-db-data:
    product-service-db-data:
    payment-service-db-data:
