services:
    payment-service:
        container_name: payment-service
        build:
            context: ./
            dockerfile: ./backend/payment-service/Dockerfile.dev
        ports:
            - '3005:3000'
        environment:
            DATABASE_URL: 'postgres://postgres:postgres@payment-service-db:5432/payment-service'
        volumes:
            - ./backend/payment-service:/home/node/app
        depends_on:
            - payment-service-db
            - user-service-db
        volumes:
            - ./backend/user-service:/home/node/app

    payment-service-db:
        container_name: payment-service-db
        image: postgres:latest
        ports:
            - '5435:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB_PAYMENT}
        volumes:
            - payment-service-db-data:/var/lib/postgresql/data

    product-service:
        container_name: product-service
        build:
            context: ./
            dockerfile: ./backend/product-service/Dockerfile.dev
        ports:
            - '3004:3004'
        environment:
            DATABASE_URL: 'postgres://postgres:postgres@product-service-db:5432/product-service'
        volumes:
            - ./backend/product-service:/home/node/app
        depends_on:
            - product-service-db

    product-service-db:
        container_name: product-service-db
        image: postgres:latest
        ports:
            - '5434:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB_PRODUCT}
        volumes:
            - product-service-db-data:/var/lib/postgresql/data

volumes:
    user-service-db-data:
    product-service-db-data:
