FROM node:20

WORKDIR /home/node/app

ENV TZ=Europe/Paris

COPY ./backend/payment-service/package*.json ./

RUN npm set strict-ssl false && npm install --include=dev

COPY ./backend/payment-service ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
